export const DAYS_TO_STALE_DATA = 2

export enum UserSyncStorageKeys {
    LAST_SCRAPE_INITIATED_AT = 'LAST_SCRAPE_INITIATED_AT',
    LAST_SCRAPE_HEARTBEAT_AT = 'LAST_SCRAPE_HEARTBEAT_AT',
    LAST_SCRAPE_STATUS = 'LAST_SCRAPE_STATUS',
    SETTING_TARGET_JOB_BOARD = 'SETTING_TARGET_JOB_BOARD',
    SETTING_TARGET_SEARCH_ACTION = 'SETTING_TARGET_SEARCH_ACTION',
}

export enum LocalStorageMetadataKeys {
    SCRAPE_AT = 'SCRAPE_AT',
}
